trigger:
- main

pool:
  vmImage: 'ubuntu-latest'


variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'Test'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: true
    projectName: 'Trend Micro'
    organization: 'b94ca70a-c110-4f1e-a54f-98475562885b'